export class RegistroCompras81Model {
  Id_RegistroCompras81: any;
  Periodo: string;
  CUO: string;
  CUO_Alfanumerico: string;
  FechaEmision: Date;
  FechaVencimiento: Date;
  TipoComprobante: string;
  Serie: string;
  AnoDUA: string;
  NumeroComprobante: string;
  ComprobantesAgrupados: string;
  TipoDocumentoIdentidad: string;
  RUCProveedor: string;
  RazonSocial: string;
  C1: number;
  C2: number;
  C3: number;
  C4: number;
  C5: number;
  C6: number;
  C7: number;
  C8: number;
  C9: number;
  C10: number;
  ImporteTotal: number;
  CodigoMoneda: string;
  TipoCambio: number;
  NCFechaEmision: Date;
  NCTipoComprobante: string;
  NCSerie: string;
  NCCodigoDependencia: string;
  NCNumeroComprobante: string;
  DefraccionFechaEmision: Date;
  DefraccionNumeroConstancia: string;
  DefraccionNumeroComprobante: string;
  ClasificacionBienes: string;
  IdentificacionContrato: string;
  ErrorTipo1: string;
  ErrorTipo2: string;
  ErrorTipo3: string;
  ErrorTipo4: string;
  CanceladoBancarizado: boolean;
  EstadoOperacion: string;
  TipoCompra: number;
  Mes: string;
  Ano: number;
  Bannys: boolean;
  Id_Empresa: number;

  constructor() {
    this.Id_RegistroCompras81 = null;
    this.Periodo = '';
    this.CUO = '';
    this.CUO_Alfanumerico = '';
    this.FechaEmision = new Date();
    this.FechaVencimiento = new Date();
    this.TipoComprobante = '';
    this.Serie = '';
    this.AnoDUA = '';
    this.NumeroComprobante = '';
    this.ComprobantesAgrupados = '';
    this.TipoDocumentoIdentidad = '';
    this.RUCProveedor = '';
    this.RazonSocial = '';
    this.C1 = 0;
    this.C2 = 0;
    this.C3 = 0;
    this.C4 = 0;
    this.C5 = 0;
    this.C6 = 0;
    this.C7 = 0;
    this.C8 = 0;
    this.C9 = 0;
    this.C10 = 0;
    this.ImporteTotal = 0;
    this.CodigoMoneda = '';
    this.TipoCambio = 0;
    this.NCFechaEmision = new Date();
    this.NCTipoComprobante = '';
    this.NCSerie = '';
    this.NCCodigoDependencia = '';
    this.NCNumeroComprobante = '';
    this.DefraccionFechaEmision = new Date();
    this.DefraccionNumeroConstancia = '';
    this.DefraccionNumeroComprobante = '';
    this.ClasificacionBienes = '';
    this.IdentificacionContrato = '';
    this.ErrorTipo1 = '';
    this.ErrorTipo2 = '';
    this.ErrorTipo3 = '';
    this.ErrorTipo4 = '';
    this.CanceladoBancarizado = false;
    this.EstadoOperacion = '';
    this.TipoCompra = 0;
    this.Mes = '';
    this.Ano = 0;
    this.Bannys = true;
    this.Id_Empresa = 0;
  }
}
